spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: __CONSUL_HTTP_PORT__
      scheme: __CONSUL_SCHEME__
      discovery:
        service-name: 'job-config'
        instance-id: job-config-${machine.ip}-${server.port}
        enabled: true
        prefer-ip-address: true
        scheme: http
    stream:
      defaultBinder: jobCommon      
      binders:
        jobCommon:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: __BK_JOB_RABBITMQ_HOST__
                port: __BK_JOB_RABBITMQ_PORT__
                username: __BK_JOB_RABBITMQ_USERNAME__
                password: __BK_JOB_RABBITMQ_PASSWORD__
                virtual-host: __BK_JOB_RABBITMQ_VHOST__
  security:
    user:
      name: __BK_JOB_SECURITY_USERNAME__
      password: __BK_JOB_SECURITY_PASSWORD__
      role: ADMIN

server:
  port: __BK_JOB_CONFIG_SERVER_PORT__
