apiVersion: v2
name: "bk-job"
description: A Helm Chart for Blueking Job
type: application
version: 0.1.13
appVersion: "3.4.0-beta.10"

dependencies:
- name: common
  version: 1.7.1
  repository: https://charts.bitnami.com/bitnami
- name: nginx-ingress-controller
  version: 7.6.17
  repository: https://charts.bitnami.com/bitnami
  condition: nginx-ingress-controller.enabled
- name: mariadb
  version: 9.4.1
  repository: https://charts.bitnami.com/bitnami
  condition: mariadb.enabled
- name: redis
  version: 14.8.7
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: mongodb
  version: 10.23.8
  repository: https://charts.bitnami.com/bitnami
  condition: mongodb.enabled
- name: rabbitmq
  version: 8.19.1
  repository: https://charts.bitnami.com/bitnami
  condition: rabbitmq.enabled
